"""Render reviewed aggregate cycle002 audit outputs; run after run_audit.py."""
from pathlib import Path
import hashlib,json
OUT=Path(__file__).resolve().parent
ROOT=OUT.parents[2]
r=json.loads((OUT/'results.json').read_text()); models=r['models']
def save(name,d): (OUT/name).write_text(json.dumps(d,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
def num(x,n=2): return f'{x:.{n}f}'.replace('.',',')
def count(x): return f'{x:,}'.replace(',','.')
def table(headers,rows): return {'headers':headers,'rows':[[str(x) for x in row] for row in rows]}
sources=[{'title':'CDC: variância e subpopulações NHANES','url':'https://wwwn.cdc.gov/nchs/nhanes/tutorials/varianceestimation.aspx'},
 {'title':'CDC: ponderação NHANES','url':'https://wwwn.cdc.gov/nchs/nhanes/tutorials/weighting.aspx'},
 {'title':'DEMO_L: escolaridade de adultos 20+','url':'https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DEMO_L.htm'},
 {'title':'DSQTOT_L: suplementos e antiácidos','url':'https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DSQTOT_L.htm'},
 {'title':'svy: regressão e análise de domínio','url':'https://svylab.com/docs/svy/tutorials/glm.html'},
 {'title':'R survey: convenções de graus de liberdade','url':'https://r-survey.r-forge.r-project.org/pkgdown/docs/reference/svyglm.html'}]
sections=[{'title':'Escopo e registro','paragraphs':['Auditoria pós-resultados do ciclo 001 corrigido, registrada localmente em 2026-09-09 antes da execução desta rodada. Usa os mesmos seis XPT, participantes e especificações. Não é replicação, nova evidência de eficácia ou validação em outra população.','Foram reproduzidas as chaves dos participantes analíticos e todas as estimativas do ciclo anterior. Os hashes dos insumos permanecem iguais. O pacote svy 0.28.0 foi instalado como dependência de desenvolvimento pelo Pipenv; o lock registra suas dependências.']},
 {'title':'Cobertura e seleção','paragraphs':['DEMO contém 11.933 pessoas, sendo 8.153 com idade ≥18. As ligações necessárias a cada pergunta deixam 6.337 adultos. A tabela usa este último denominador: as retenções não representam participação no inquérito ou na população inteira.','Os 273 participantes de 18–19 anos nas junções têm DMDEDUC2 ausente por elegibilidade da variável (20+). Portanto, a amostra final 20–80 não inclui os mais jovens do protocolo 18+. Ausência estrutural não é recusa. A idade máxima também é truncada na divulgação.','A renda/PIR falta em 831 dos 6.337 adultos. H1/H3 têm 1.351 recordatórios indisponíveis e pesos dietéticos zero. Essas perdas se sobrepõem: contagens marginais não podem ser somadas. Atribuições sequenciais dependem da ordem dos filtros e não revelam causas clínicas de ausência.'],
  'table':table(['Modelo','Após junções','Analisados','Retenção','Excluídos após junções'],[[h,count(m['n_joined']),count(m['n_retained']),num(100*m['retention'])+'%',count(m['n_joined']-m['n_retained'])] for h,m in models.items()])},
 {'title':'Desigualdade dos pesos','paragraphs':['Kish = (soma dos pesos)²/soma dos pesos² descreve apenas a desigualdade de ponderação. Não incorpora clusters, estratificação, desfecho ou covariáveis e não deve ser interpretado como tamanho efetivo completo da regressão.','Não foram truncados, recalibrados ou substituídos pesos. As somas após seleção não recuperam automaticamente a população-alvo: o ajuste original de não resposta do inquérito não elimina seleção adicional por casos completos.'],
  'table':table(['Modelo','Peso','N','Kish','CV','Fração dos pesos no 1% maior'],[[h,m['weight'],count(m['n_retained']),num(m['weight_summary']['kish_n'],1),num(m['weight_summary']['cv'],3),num(100*m['weight_summary']['top_1pct_weight_share'])+'%'] for h,m in models.items()])},
 {'title':'Variância: comparação independente executada','paragraphs':['A matriz de covariáveis foi compartilhada para isolar o cálculo estatístico. Em svy, o desenho foi definido com todos os registros de peso positivo, estrato e PSU antes de selecionar o domínio de casos completos com where. Foi usada aproximação com reposição, sem correção de população finita.','Todos os 15 estratos e 30 PSUs do desenho têm participantes nas três amostras analíticas. Nesse caso concreto, o cálculo Taylor anterior coincide numericamente com o cálculo que preserva o desenho completo. Isso não autoriza reutilizar a rotina anterior em domínios que esvaziem PSUs: ela ignora estratos com menos de duas PSUs observadas.','A comparação verifica cada coeficiente e seu erro-padrão, não a matriz completa de covariância ou testes conjuntos. Não valida mensuração, escolha de confundidores, seleção de casos completos, causalidade ou transporte para HA/autismo/TDAH.'],
  'table':table(['Modelo','N no desenho completo','Colunas/rank da matriz','Maior diferença absoluta: coeficiente','Maior diferença relativa: erro-padrão'],[[h,count(m['variance_comparison']['full_design_n']),str(m['variance_comparison']['matrix_columns'])+'/'+str(m['variance_comparison']['matrix_rank']),f"{m['variance_comparison']['max_abs_beta_difference']:.3g}",f"{m['variance_comparison']['max_relative_se_difference']:.3g}"] for h,m in models.items()])},
 {'title':'Sensibilidade aos graus de liberdade','paragraphs':['O ciclo 001 usa t com 15 graus (30 PSUs − 15 estratos). O padrão de svy 0.28.0 subtrai k−1 e aplica piso de 1: max(1, 15−(k−1)). Com k=17 em H1/H2 e k=18 em H3, todos chegam a 1 grau. Esse piso é comportamento do pacote, não demonstração de que 1 seja a escolha correta para estes modelos.','Os coeficientes e erros-padrão são os mesmos, mas p-valores e intervalos dependem da distribuição de referência. A documentação de R survey descreve tanto a convenção residual quanto a opção de usar os graus do desenho; alerta que a primeira pode ser muito conservadora para covariáveis individuais. Não foi executado R nesta rodada.','Recalculando p a partir de svy com 15 graus, reproduzimos o ciclo 001 e a mesma família FDR de oito termos. Com o padrão de 1 grau, nenhum teste tem q<0,05. Essa comparação é sensibilidade à convenção, não oito novas descobertas. Nenhuma das duas saídas substitui silenciosamente a outra; futuras especificações devem justificar complexidade e graus antes dos resultados.'],
  'table':table(['Modelo/termo','p: 15 graus','p: svy padrão (1)','q: 15 graus','q: svy padrão (1)'],[[x['model']+' / '+x['term'],f"{x['cycle001_p']:.6g}",f"{x['svy_p']:.6g}",f"{x['q_design_df15']:.6g}",f"{x['q_svy_default']:.6g}"] for x in r['primary_df_sensitivity']])},
 {'title':'Magnésio: limites da ausência registrada','paragraphs':['Na amostra H3, 1.401 pessoas declaram uso de algum suplemento, mas DSQTMAGN está ausente. Isso não comprova que tomaram magnésio com dose desconhecida: pode envolver produto sem magnésio ou incompletude da composição. O nome operacional SUPP_MAG_UNQUANT do ciclo anterior não resolve essa ambiguidade.','Há 28 pessoas com DSD010=2 e magnésio quantificado; suplementos e antiácidos têm indicadores distintos. Não concluir inconsistência nem zerar automaticamente esses valores. A recodificação e a distinção entre não exposição e quantidade desconhecida exigem detalhamento de produtos/antiácidos em uma próxima auditoria.','O ciclo 001 permanece numericamente preservado. H3 é estimável com limites de mensuração; essa checagem não confirma forma química, uso de magnésio por todos os usuários de suplemento, ou indicação clínica.'],
  'table':table(['Categoria observada em H3','N'],[[k,v] for k,v in models['H3']['supplement_categories'].items()])},
 {'title':'Conferência de leitura e códigos','paragraphs':['Foram conferidos totais do codebook DSQTOT_L: 3.762 usuários, 2.969 não usuários, 1.613 valores presentes de magnésio e 2.106 pesos WTDRD1 zero. Os 2.106 zeros de peso estavam representados como floats SAS diminutos e foram normalizados pela regra existente. Essa checagem cobre esses campos, não todos os zeros de todos os componentes.']},
 {'title':'Decisão e próximos testes','paragraphs':['H1, H2 e H3: estimable_with_limits para associações na amostra de casos completos, com estimadores e erros-padrão conferidos. A robustez da inferência depende da escolha de graus, da seleção e da mensuração. Os grupos HA, autismo e TDAH continuam not_assessed.','Estado na data desta auditoria: definir complexidade e graus de liberdade antes de novas especificações; auditar composição de suplementos/antiácidos e códigos de ausência; avaliar seleção/dados ausentes; só então registrar formas não lineares e validação por PSU/onda. Não executar uma busca de especificações que produzam significância.','Atualização posterior: o ciclo 003 auditou produtos e antiácidos; o ciclo 004 registrou 15 graus do desenho como convenção principal segundo o NCHS e testou reponderação pela seleção observável. As pendências atuais são a nova especificação de H3, seleção não observada, formas não lineares e validação independente.']}]
# Full local audit includes all exclusion and PSU counts, without individual records.
lines=['# Auditoria de seleção, pesos e variância — ciclo 002','','[Protocolo local](protocol.md) · [Agregados e proveniência](results.json)','','## Mapa de mensuração','','SEQN: chave individual dentro da mesma onda; não publicado neste relatório. H1 usa DR1TCAFF/100 → SLD012, com energia, idade/idade², sexo registrado, raça/etnia, escolaridade e PIR. H2 usa SLEEP_CAT e PAD680/60 → soma DPQ sem DPQ030. H3 usa DR1TMAGN/100, DSQTMAGN/100 e indicador de ausência → SLD012, com os mesmos ajustes de H1. Exposições continuam transversais e com janelas diferentes. Campos originais, motivos de exclusão e pesos estão nas tabelas abaixo.','']
def markdown_section(s):
 out=['## '+s['title'],'']
 for p in s.get('paragraphs',[]): out += [p,'']
 if 'table' in s:
  t=s['table'];out += ['| '+' | '.join(t['headers'])+' |','|'+'|'.join(['---']*len(t['headers']))+'|']
  out += ['| '+' | '.join(row)+' |' for row in t['rows']];out+=['']
 return out
for s in sections: lines+=markdown_section(s)
for h,m in models.items():
 lines+=markdown_section({'title':h+' — perdas sequenciais (ordem explícita)','table':table(['Etapa','Excluídos nesta etapa','Restantes'],[[x['step'],x['excluded'],x['remaining']] for x in m['flow']])})
 lines+=markdown_section({'title':h+' — ausência marginal sobreposta','paragraphs':['Denominador de cada linha: 6.337 adultos após junções. Valores inválidos são códigos observados, sem inferir sua causa além do codebook.'], 'table':table(['Campo','Ausente bruto','Código inválido/peso zero','Valores inválidos: contagem','Total não utilizável'],[[x['variable'],x['raw_missing'],x['invalid_or_zero_weight'],str(x['invalid_raw_values']),x['unusable_total']] for x in m['marginal']])})
 lines+=markdown_section({'title':h+' — cobertura por estrato/PSU','table':table(['Estrato','PSU','Peso positivo (todas idades)','Adultos ligados com peso positivo','Retidos'],[[x['stratum'],x['psu'],x['positive_weight_n'],x['joined_adults'],x['retained']] for x in m['psu_cells']])})
lines+=['## Fontes','']+[f"- [{s['title']}]({s['url']})" for s in sources]
lines+=['','## Reprodução','','```bash','MPLCONFIGDIR=/tmp/science-matplotlib PIPENV_VENV_IN_PROJECT=1 pipenv run python research/discoveries/cycle-002/run_audit.py','PIPENV_VENV_IN_PROJECT=1 pipenv run python research/discoveries/cycle-002/render_audit.py','```','']
(OUT/'data-audit.md').write_text('\n'.join(lines))
review='Auditoria de implementação e seleção, não replicação. Erros-padrão coincidem com svy; p-valores não coincidem por padrão porque as convenções de graus de liberdade diferem. Atualização posterior: os ciclos 003 e 004 trataram, respectivamente, a mensuração de magnésio e a convenção de inferência/seleção observável.'
save('public-dossier.json',{'schema_version':1,'review_note':review,'sections':sections})
cycle={'schema_version':1,'id':'cycle-002','status':'completed','data_kind':'empirical_aggregate','title':'Auditoria de perdas, pesos e variância do ciclo 001','summary':'Reconstituição das amostras e comparação Taylor com svy: erros-padrão reproduzidos e perdas após junções. Os ciclos 003–004 registram atualizações posteriores de mensuração e inferência.','population':'NHANES 2021–2023: 6.337 adultos após junções por hipótese, 4.194–4.522 casos completos de 20–80 anos; HA/autismo/TDAH não avaliados.','completed_at':'2026-09-09',
'findings':[
 {'question':'Quanto se perde após as junções por hipótese?','estimate':'H1: 4.211/6.337 (66,45%); H2: 4.522/6.337 (71,36%); H3: 4.194/6.337 (66,18%)','uncertainty':'Contagens exatas dos arquivos locais; não são estimativas de prevalência e não requerem IC.','sample':'6.337 adultos após junções; antes delas, DEMO contém 8.153 adultos.','interpretation':'273 pessoas de 18–19 anos não têm a escolaridade 20+ exigida. Ausência de renda, dieta e sintomas explica outras perdas observáveis, com sobreposição.'},
 {'question':'Qual é a concentração dos pesos analíticos?','estimate':'Kish: H1=2.460,2; H2=2.957,1; H3=2.450,7','uncertainty':'Indicadores descritivos dos pesos; não são N efetivos completos do desenho.','sample':'WTDRD1 em H1/H3; WTMEC2YR em H2; sem truncamento de pesos.','interpretation':'O 1% de maiores pesos concentra aproximadamente 4,4–5,4% da soma; seleção por casos completos permanece uma limitação.'},
 {'question':'A implementação anterior reproduz a variância de um pacote independente?','estimate':'Diferença relativa máxima nos erros-padrão <2×10⁻¹³; coeficientes diferem <6×10⁻¹³','uncertainty':'Concordância numérica por coeficiente; não é IC de efeito nem validação causal.','sample':'svy 0.28.0, domínio de casos completos no desenho completo; 15 estratos/30 PSUs representados em cada modelo.','interpretation':'Coeficientes e erros-padrão conferidos neste domínio; a rotina anterior não deve ser generalizada a domínios com PSUs vazias.'},
 {'question':'Os testes dependem da convenção de graus de liberdade?','estimate':'15 graus no ciclo 001; 1 no padrão svy. Com o padrão svy, nenhum dos oito q-valores é <0,05.','uncertainty':'Mesmos coeficientes e erros-padrão; distribuições t diferentes. Com 15 graus, svy reproduz os p/q originais.','sample':'17 coeficientes em H1/H2 e 18 em H3; svy aplica max(1, 15−(k−1)).','interpretation':'Relatar as duas convenções. O piso de 1 não prova superioridade; definir complexidade e inferência antes de novas análises.'}],
'figures':[{'path':'figures/selection.png','alt':'Participantes retidos e excluídos nas três hipóteses','caption':'NHANES 2021–2023: contagens não ponderadas após junções de adultos; não representa taxa populacional de resposta.'},{'path':'figures/weights.png','alt':'Comparação entre N observado e indicador de Kish','caption':'WTDRD1 para H1/H3, WTMEC2YR para H2; Kish reflete somente desigualdade dos pesos, sem IC ou correção por clusters.'}],
'limitations':['Auditoria na mesma onda e nos mesmos participantes, sem replicação independente.','Inferência sensível à convenção de graus; modelos têm 17–18 coeficientes para 15 graus do desenho.','Casos completos podem introduzir seleção não resolvida pelos pesos originais.','DSQTMAGN ausente não identifica por si só consumo de magnésio com dose desconhecida.','Não identifica altas habilidades, autismo ou TDAH; não orienta dose individual.'],
'sources':sources,'reproducibility':{'command':'MPLCONFIGDIR=/tmp/science-matplotlib PIPENV_VENV_IN_PROJECT=1 pipenv run python research/discoveries/cycle-002/run_audit.py','code_revision':'working tree; run_audit.py sha256='+hashlib.sha256((OUT/'run_audit.py').read_bytes()).hexdigest()+'; svy 0.28.0; additional hashes in results.json','input_sha256':r['input_sha256']}}
save('cycle.json',cycle)
print('Rendered cycle002 report and public manifest')
